---
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        health:
          enabled: false
        git:
          uri: git@github.com:pbrown-gh/this-would-be-a-real-config-repo.git
  security:
    user:
      name: fakeUsername
      password: fakePassword

management:
  endpoints:
    web:
      exposure:
        include:*:

eureka:
  instance:
    preferIpAddress: true
    nonSecurePort: ${server.port:8888}
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://fakeUsername:fakePassword@discoveryserver:8761/eureka/

# Defines the port where the config server is running so that rest of the services can pick up
# their external configurations
server:
  port: 8888
